import { atom } from 'recoil'
import { v4 } from 'uuid'

export const stepState = atom({
  key: `stepState/${v4()}`,
  default: 0,
  dangerouslyAllowMutability: true,
})

export const biddingInfoState = atom({
  key: `biddingInfoState/${v4()}`,
  default: {
    isFileCreated: false,
    selectedTime: '0',
    courtFullName: '',
    mstSeq: 0,
    state: 0,
    infoId: '',
    caseNo: '',
    sagunNum: '',
    mulNo: '',
    usage: '',
    etcAddress: '',
    roadAddress: '',
    sagunAddr: '',
    ipchalDate: '',
    biddingDate: '',
    biddingInfos: [
      {
        biddingTime: '',
        appraisalAmount: 0,
        minimumAmount: 0,
        bidDeposit: 0,
      },
    ],
    biddingInfo: {
      biddingTime: '',
      appraisalAmount: 0,
      minimumAmount: 0,
      bidDeposit: 0,
    },
    bidder: '',
    bidderNum: 0,
    biddingPrice: 0,
    depositPrice: 0,
    bidWay: '',
    bidCorpYn: [''],
    bidName: [''],
    bidPhone1: [''],
    bidPhone2: [''],
    bidPhone3: [''],
    bidPhone: [''],
    bidIdNum1: [''],
    bidIdNum2: [''],
    bidIdNum: [''],
    bidAddr: [''],
    bidAddrDetail: [''],
    bidCorpNum1: [''],
    bidCorpNum2: [''],
    bidCorpNum3: [''],
    bidCorpNum: [''],
    bidCorpRegiNum1: [''],
    bidCorpRegiNum2: [''],
    bidCorpRegiNum: [''],
    bidJob: [''],
    agentYn: '',
    agentName: '',
    agentPhone1: '',
    agentPhone2: '',
    agentPhone3: '',
    agentPhone: '',
    agentIdNum1: '',
    agentIdNum2: '',
    agentIdNum: '',
    agentAddr: '',
    agentAddrDetail: '',
    agentJob: '',
    agentRel: '',
    pdfFile: new Blob(),
    reqCourtName: '',
    idcode: '',
    aesUserId: '',
    bidders: [],
    imageFile: '',
    isModalOpen: false,
    shareWay: 'S',
    numerator: [''],
    denominator: [''],
    mulSeq: '',
    mandates: [
      {
        peopleSeq: 0,
        name: '',
        mandateYn: '',
      },
    ],
    pdfPassword: '',
    fileName: '',
    searchResults: [] || null,
    selectedCase: '',
    selectedYear: '',
    searchResultState: 1,
    tokenOk: false,
  },
  dangerouslyAllowMutability: true,
})
